### PR TITLE
replaced by configure script

### PR DESCRIPTION
**Pull request by malb**
If we agree that `configure` is feature complete, we should remove `rebuild.sh` to avoid surprises in the future.

### CODE REVIEW

**Comment by lducas** [comment]
Please document how to use the same options that `rebuild.sh` offered within `configure` though :)

**Comment by malb** [comment]
> Please document how to use the same options that `rebuild.sh` offered within `configure` though :)

Where? It's all in `./configure --help` at the moment.

**Comment by malb** [comment]
Can I merge this?

**Comment by joerowell** [comment]
I agree -- I didn't see anything missing and rebuild always confuses me.

**Comment by lducas** [comment]
+1

**Comment by cr-marcstevens** [comment]
+1

**Pull request merged**
