### PR TITLE
Add LICENSE and copyright statements to source files

### PR DESCRIPTION
**Pull request by cr-marcstevens**

### CODE REVIEW

**Comment by malb** [comment]
Looks good to me. We need consent from everyone who had code included in this repo for this PR to be accepted though.

**Comment by cr-marcstevens** [comment]
Tagging @lducas @malb @verdiverdiverdi @ElenaKirshanova @J08nY @blowfish880 @WvanWoerden @joerowell for approval for the GPL license for G6K. 
This is to resolve Issue #74 on missing copyright license of G6K.

**Comment by J08nY** [comment]
Works for me.

**Comment by joerowell** [comment]
Suits me.

**Comment by joerowell** [comment]
Suits me.

**Comment by cr-marcstevens** [comment]
I see I missed @GottfriedHerold, anyone else I missed?

**Comment by malb** [comment]
I think that's it.

**Comment by cr-marcstevens** [comment]
We have now approval from: @GottfriedHerold @joerowell @J08nY @WvanWoerden @verdiverdiverdi @malb @lducas @cr-marcstevens 
Thank you all!

Approval is still missing from: @ElenaKirshanova @blowfish880

**Comment by blowfish880** [comment]
Sounds good. (Sorry for the delay.)

**Comment by ElenaKirshanova** [comment]
Sorry, I missed it.
It suits me too.

**Pull request merged**
