### PR TITLE
Port to Python 3

### LINKED ISSUE #2: Port to Python 3
Python 2.7 will not be maintained from 2020: https://pythonclock.org/

### PR DESCRIPTION
**Pull request by J08nY**
Fixes #2.

All tests pass with this, most changes done by `2to3`, some by hand.

### CODE REVIEW

**Comment by J08nY** [comment]
This PR also allows for proper installation of the whole package (i.e. it adds the g6k.algorithms and g6k.utils packages and also the spherical_coding data for simhash).

**Comment by malb** [comment]
This looks good to me, thanks! 

We'll need to make the explicit decision to disable Python 2. I think that makes sense given https://pythonclock.org/ but it's worth discussing explicitly.

This also means G6K won't work inside Sage as Sage's Python 3 transition isn't complete. Might we worth testing it in Sage's Python 3 WIP?

**Comment by J08nY** [comment]
> This looks good to me, thanks!
> 
> We'll need to make the explicit decision to disable Python 2. I think that makes sense given [pythonclock.org](https://pythonclock.org/) but it's worth discussing explicitly.
> 
> This also means G6K won't work inside Sage as Sage's Python 3 transition isn't complete. Might we worth testing it in Sage's Python 3 WIP?

I could try to make it work with both versions, just some from `__future__` imports would be necessary, and maybe a reformulation of some conditions (to not compare stuff with `None`). Do you think it would be worth it to keep the compatibility?

I would specifically like to see the addition of the `algorithms` package and `spherical_coding` change to be merged, so I am willing to work for that.

**Comment by malb** [comment]
If you're up for making it work for Python 2 and 3, that'd be fab, e.g. for older copies of Sage. I definitely want to see this merged too.

**Comment by malb** [comment]
Closing this due to #17. Thank you!

**Pull request closed without merging**
