### PR TITLE
Parallelize

### PR DESCRIPTION
**Pull request by lducas**
Parallelizing minor tasks, just because it's not that hard. In fact, grow_db was a mess.

### CODE REVIEW

**Comment by lducas** [comment]
CPUs

**Comment by cr-marcstevens** [comment]
The added timing code in shrinkdb seems not useful, artifact?

**Comment by lducas** [comment]
Oopsies. Is that all ?

**Comment by cr-marcstevens** [comment]
I don't think this branch should be merged!

This branch completely removes `parallel_sort_cdb()` and just replaces it with a GNU parallelized version of std::sort.
This is fine for several sieving algorithms, but others require additional structure in cdb.
parallel_sort_cdb made sure this additional structure is kept, while std::sort or any parallel version thereof does not.

**Comment by lducas** [comment]
ok, lets revert to just the first two commits then.

**Comment by cr-marcstevens** [comment]
I think there is more interesting stuff to keep, but this branch should at least revert to using the original parallel_sort_cdb() again everywhere.
Then if we want to optimize with gnu parallel sort then we can do that within parallel_sort_cdb. 
But I have a working partition subroutine that works better than gnu parallel's, so I'm hoping it also results in a better parallel sorting algo without the extra gnu parallel lib dependency.

**Comment by lducas** [comment]
Voila, branch is cleaned up.

**Comment by cr-marcstevens** [comment]
Great! Then I'll rebase my stuff on your branch.

**Comment by lducas** [comment]
Do you mean: you have more to contribute to this branch before merging it ?

**Comment by cr-marcstevens** [comment]
It's in the same line, but feel free to merge. Then I'll just make another PR.

**Pull request merged**
