### PR TITLE
Add COPYING file & copyright statements in source code files

### PR DESCRIPTION
**Pull request by cr-marcstevens**

### CODE REVIEW

**Comment by malb** [comment]
Did you mean to go for LGPL?

**Comment by cr-marcstevens** [comment]
What do you mean?

The COPYING and copyright statement are as used in fplll.

**Comment by cr-marcstevens** [comment]
I thought that was the copyright license you suggested.

**Comment by malb** [comment]
FPLLL is LGPL, FPyLLL is GPL which is stricter. I suggested the latter because we build on FPyLLL.

**Comment by cr-marcstevens** [comment]
Ah. But I didn't know, nor expected, that fplll and fpylll actually had different licenses..
I guess I also overlooked the key word 'lesser' as I just copied the text blocks.

**Pull request closed without merging**
